// <auto-generated />
using System;
using IdealTimeTracker.WPF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdealTimeTracker.WPF.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20240906141641_noneOptiosn")]
    partial class noneOptiosn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.29");

            modelBuilder.Entity("IdealTimeTracker.WPF.Model.ApplicationConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationConfigurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IDEAL TIME",
                            Value = new TimeSpan(0, 0, 1, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Name = "WORKING TIME",
                            Value = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Name = "SYNC TIME ONE",
                            Value = new TimeSpan(0, 4, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            Name = "SYNC TIME TWO",
                            Value = new TimeSpan(0, 13, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("IdealTimeTracker.WPF.Model.User", b =>
                {
                    b.Property<string>("EmpId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportingTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("EmpId");

                    b.HasIndex("EmpId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            EmpId = "ADMIN",
                            Email = "admin@example.com",
                            IsActive = true,
                            Name = "Admin User",
                            PassWord = "ADMIN",
                            Role = "admin"
                        });
                });

            modelBuilder.Entity("IdealTimeTracker.WPF.Model.UserActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activity")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CountPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationInMins")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserActivities");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Activity = "login",
                            DurationInMins = 0,
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            Activity = "logout",
                            DurationInMins = 0,
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            Activity = "Others",
                            DurationInMins = 0,
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            Activity = "tea break",
                            CountPerDay = 2,
                            DurationInMins = 15,
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            Activity = "lunch break",
                            CountPerDay = 2,
                            DurationInMins = 30,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("IdealTimeTracker.WPF.Model.UserLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("IdealTimeTracker.WPF.Model.UserLog", b =>
                {
                    b.HasOne("IdealTimeTracker.WPF.Model.UserActivity", "UserActivity")
                        .WithMany()
                        .HasForeignKey("ActivityId");

                    b.Navigation("UserActivity");
                });
#pragma warning restore 612, 618
        }
    }
}
